# Generated by Django 5.0 on 2023-12-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0002_alter_notes_options_userprofileinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="picture",
            field=models.ImageField(blank=True, upload_to="profile_pics"),
        ),
    ]
